In [2]:
import pandas as pd
import numpy as np

In [4]:
b = pd.read_parquet('C:/Users/caiho/Desktop/EDS_factor_model/data/market_value.parquet')
b

         FACTSET_ID       DATE CURRENCY     MARKETCAP
0          DYJJZ3-R 2020-01-01      USD    571.448519
1          BS9ZK4-R 2020-01-01      USD  26440.666487
2          NYKB2Q-R 2020-01-01      JPY   5519.184691
3          LRG9XL-R 2020-01-01      JOD     10.150000
4          JMD5NG-R 2020-01-01      CNY   3496.720107
...             ...        ...      ...           ...
79181990   GZGJTY-R 2025-12-12      USD    335.399995
79181991   JCNM95-R 2025-12-12      USD   4384.876913
79181992   CW9B38-R 2025-12-12      CNY   9192.322998
79181993   BQT8YS-R 2025-12-12      INR  18054.157720
79181994   XRB5RR-R 2025-12-12      SAR   7198.764919

[79181995 rows x 4 columns]

In [3]:
pd.read_parquet('C:/Users/caiho/Desktop/EDS_factor_model/data/enterprise_value.parquet')

          FACTSET_ID       DATE  ENTERPRISE_VALUE EV_COMPONENTS_DATE
0           B00044-R 2020-01-01      82742.722939               None
1           VG0PKZ-R 2020-01-01         30.691572         2019-12-31
2           H0BHCC-R 2020-01-01      17255.190582               None
3           WSYYG7-R 2020-01-01       6623.675230         2019-12-31
4           X479N0-R 2020-01-01        695.156054         2019-12-31
...              ...        ...               ...                ...
253816461   TD28HD-R 2025-12-11         57.580968         2025-09-30
253816462   GZBZL4-R 2025-12-11      85023.034573         2025-09-30
253816463   GZC0CX-R 2025-12-11       1034.020354         2025-09-30
253816464   TD2BMG-R 2025-12-11       4436.675129         2008-12-31
253816465   XRB643-R 2025-12-11         14.073463         2025-06-30

[253816466 rows x 4 columns]

In [2]:
df = pd.read_parquet('C:/Users/caiho/Desktop/EDS_factor_model/data/fundamentals.parquet')
df

,FACTSET_ID,DATE,SALES_LTM,SALES_NTM,COGS_LTM,COGS_NTM,EBITDA_LTM,EBITDA_NTM,EPS_LTM,EPS_NTM
0,B007G7-R,2019-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B007LC-R,2019-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,B00DXJ-R,2019-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B00FG1-R,2019-01-01,274.874480,294.23758,NaN,NaN,156.3113,180.09314,1.816866,2.033709
4,B00M5L-R,2019-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
134132505,XR7GZL-R,2025-11-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134132506,XR82VW-R,2025-11-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134132507,XR8586-R,2025-11-13,25356.200000,28105.40000,NaN,21074.20000,NaN,NaN,133.220000,160.061000
134132508,XR8872-R,2025-11-13,0.972358,11.96410,NaN,8.58137,-15.0355,-14.66630,-0.539788,-0.188074
134132509,XR9F0R-R,2025-11-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
np.sort(df["DATE"].unique())

array([datetime.date(2019, 1, 1), datetime.date(2019, 1, 2),
       datetime.date(2019, 1, 3), ..., datetime.date(2025, 11, 11),
       datetime.date(2025, 11, 12), datetime.date(2025, 11, 13)],
      shape=(1793,), dtype=object)

In [6]:
df.dropna()

,FACTSET_ID,DATE,SALES_LTM,SALES_NTM,COGS_LTM,COGS_NTM,EBITDA_LTM,EBITDA_NTM,EPS_LTM,EPS_NTM
9,B018KB-R,2019-01-01,843.30927,919.3478,688.65204,744.09015,153.90796,173.307080,0.160436,0.184266
11,B01HWF-R,2019-01-01,1843.53080,1977.6931,1484.83300,1595.40870,-146.52882,-35.146812,-6.002156,-1.730542
28,B02ZTY-R,2019-01-01,119685.11000,137786.4000,106707.54000,122437.16000,9234.92100,10721.796000,1.975770,2.331731
31,B03872-R,2019-01-01,34663.48000,39548.2660,4127.23000,5078.52050,23884.56800,26992.110000,34.246136,38.897034
33,B03BC4-R,2019-01-01,10691.99800,12248.4150,5537.69870,6212.63900,1757.13700,2031.295000,0.781877,0.900822
...,...,...,...,...,...,...,...,...,...,...
134132488,XQPQNH-R,2025-11-13,17794.10000,18862.1000,15970.10000,16904.50000,1162.86000,1232.900000,0.485260,0.566849
134132491,XQRMDD-R,2025-11-13,14871.40000,17236.2000,9709.21000,10542.30000,1493.85000,1920.970000,10.961100,14.492800
134132493,XQVGNX-R,2025-11-13,188.94500,559.7230,75.21200,255.88700,-61.31730,132.640000,-9.809940,-1.663880
134132500,XR06QC-R,2025-11-13,16.30810,23.9549,7.01063,9.42169,-15.26880,-15.292100,-1.998530,-1.426530
134132501,XR0GGW-R,2025-11-13,1012.12000,1140.3100,286.15900,334.89900,508.45200,617.745000,5.302390,6.151770